#!/usr/bin/env python3
"""Create a clean-HEAD/config/evaluator/SFT freeze receipt for promotion-v4."""
from __future__ import annotations
import argparse, hashlib, json, subprocess, platform
from pathlib import Path

def digest(path): return "sha256:"+hashlib.sha256(Path(path).read_bytes()).hexdigest()
def main(argv=None):
 p=argparse.ArgumentParser(); p.add_argument("--output",type=Path,required=True); p.add_argument("--sft-manifest",type=Path,default=Path("artifacts/tier1_p232_atomic_factorial_10seed/sft_checkpoints/sft_seed_17.json")); p.add_argument("--canonical-manifest",type=Path,default=Path("artifacts/tier1_p232_atomic_factorial_10seed/run_manifest.json")); p.add_argument("--shortcut-result",type=Path,default=Path("artifacts/tier1_p232_atomic_factorial_10seed/shortcut_probe_strict/shortcut_probe_result.json")); a=p.parse_args(argv)
 head=subprocess.check_output(["git","rev-parse","HEAD"],text=True).strip(); clean=not subprocess.check_output(["git","status","--porcelain"],text=True).strip(); config={"sft_steps":16,"finetune_steps":64,"batch_size":32,"hidden_dim":24,"learning_rate":0.002,"minibatch_epochs":2,"branch_formulation":"sibling_advantage","gradient_mode":"sum","top1_gap_threshold":0.05,"bootstrap_replicates":5000}; evaluator_files=["research_strategy_optimization/evaluation/tier1_p231_diagnostics.py","research_strategy_optimization/evaluation/tier1_differentiable_suite.py","research_strategy_optimization/environments/tier1_tabular_env.py","research_strategy_optimization/schemas.py"]; evaluator_hash="sha256:"+hashlib.sha256(b"".join(Path(x).read_bytes() for x in evaluator_files)).hexdigest(); sft=json.loads(a.sft_manifest.read_text()) if a.sft_manifest.exists() else {}; canonical=json.loads(a.canonical_manifest.read_text()) if a.canonical_manifest.exists() else {}; runtime=f"python={platform.python_version()}|platform={platform.platform()}"; receipt={"schema_version":"pesco_promotion_v4_freeze_receipt_v0.2","status":"FROZEN_FOR_PROMOTION_V4" if clean else "NOT_FROZEN","clean_commit":clean,"commit":head,"config":config,"config_digest":"sha256:"+hashlib.sha256(json.dumps(config,sort_keys=True,separators=(",",":")).encode()).hexdigest(),"evaluator_digest":evaluator_hash,"container_runtime":runtime,"container_digest":"sha256:"+hashlib.sha256(runtime.encode()).hexdigest(),"sft_checkpoint_digest":sft.get("state_dict_sha256"),"canonical_pair_digest":canonical.get("diagnostics",{}).get("canonical_pair_digest"),"strict_shortcut_digest":digest(a.shortcut_result) if a.shortcut_result.exists() else None,"method_matrix":["GRPO-Atomic","Atomic+State","Atomic+Branch","Atomic+Flip","Atomic+State+Branch","Atomic+State+Flip","Atomic+Branch+Flip","PESCO-Full"],"bootstrap_definition":"paired_two_way_seed_question_cluster","bootstrap_replicates":5000,"canonical_pair_threshold":0.05,"private_access_completed":False,"access_sentinel_absent_before_run":True}; a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(receipt,indent=2,ensure_ascii=False,sort_keys=True)); print(json.dumps(receipt,ensure_ascii=False,indent=2)); return 0 if receipt["status"].startswith("FROZEN") else 2
if __name__=="__main__": raise SystemExit(main())
