#!/usr/bin/env python3
"""Cheap attribution smoke for adapter-vs-policy authenticity."""
from __future__ import annotations
import argparse, json, subprocess, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def main(argv=None):
    p=argparse.ArgumentParser(); p.add_argument('--dataset',type=Path,required=True); p.add_argument('--output',type=Path,required=True); p.add_argument('--seeds',type=int,nargs='+',default=(17,23,29)); p.add_argument('--branch-formulation', choices=('sibling_advantage','expected_utility','utility_cross_entropy','soft_utility_cross_entropy','utility_improvement_soft_ce','top1_hinge'), default='expected_utility'); p.add_argument('--gradient-mode', choices=('sum','pcgrad'), default='sum'); p.add_argument('--pcgrad-aux-pair', action='store_true'); p.add_argument('--pcgrad-aux-orthogonal', action='store_true'); p.add_argument('--branch-head-isolated', action='store_true'); p.add_argument('--flip-head-isolated', action='store_true'); p.add_argument('--atomic-target-weight', type=float, default=0.0); p.add_argument('--branch-loss-weight', type=float, default=.30); p.add_argument('--pairwise-weight', type=float, default=.10); p.add_argument('--flip-reference-kl-weight', type=float, default=.5); p.add_argument('--learning-rate', type=float, default=.002); a=p.parse_args(argv)
    runroot=a.output.parent/(a.output.stem+'_runs'); runroot.mkdir(parents=True,exist_ok=True); rows=[]
    for seed in a.seeds:
        out=runroot/f'seed_{seed}'; marker=out/'p231_result.json'
        if not marker.exists():
            cmd=[sys.executable,str(ROOT/'scripts/run_tier1_p233_chunk.py'),'--dataset',str(a.dataset),'--output-dir',str(out),'--seed',str(seed),'--methods','Atomic+State+Branch','Atomic+State+Flip','PESCO-Full','--splits','tune','--finetune-steps','64','--sft-steps','128','--hidden-dim','32','--batch-size','64','--learning-rate',str(a.learning_rate),'--branch-loss-weight',str(a.branch_loss_weight),'--pairwise-weight',str(a.pairwise_weight),'--flip-reference-kl-weight',str(a.flip_reference_kl_weight),'--atomic-target-weight',str(a.atomic_target_weight),'--gradient-mode',str(a.gradient_mode),'--branch-formulation',str(a.branch_formulation)] + (['--pcgrad-aux-pair'] if a.pcgrad_aux_pair else []) + (['--pcgrad-aux-orthogonal'] if a.pcgrad_aux_orthogonal else []) + (['--branch-head-isolated'] if a.branch_head_isolated else []) + (['--flip-head-isolated'] if a.flip_head_isolated else [])
            subprocess.run(cmd,check=True)
        d=json.loads(marker.read_text()); logs=d.get('training_logs',{}).get(str(seed),{})
        for method in ('Atomic+State+Branch','Atomic+State+Flip','PESCO-Full'):
            log=logs.get(method,{})
            rows.append({'seed':seed,'method':method,'trunk_parameter_delta':log.get('parameter_deltas',{}).get('trunk',0.0),'action_head_parameter_delta':log.get('parameter_deltas',{}).get('action_head',0.0),'flip_head_parameter_delta':log.get('parameter_deltas',{}).get('flip_head',0.0),'state_head_parameter_delta':log.get('parameter_deltas',{}).get('state_head',0.0),'action_logits_change_mean_abs':log.get('action_logits_change_mean_abs',0.0),'selected_action_change_rate':log.get('selected_action_change_rate',0.0),'external_adapter_overrides_action_logits':log.get('external_adapter_overrides_action_logits',False),'no_external_adapter_overrides_action_logits':log.get('no_external_adapter_overrides_action_logits',True),'freeze_action_checkpoint':log.get('freeze_action_checkpoint',False)})
    full_rows=[r for r in rows if r['method']=='PESCO-Full']
    out={'schema_version':'pesco_p233_r1_attribution_smoke_v1','rows':rows,'rf_only':'independent strict sklearn shortcut artifact','sft_plus_rf':'independent SFT action baseline plus strict sklearn probe; not embedded in PESCO','full_without_rf':bool(full_rows) and all(not r['external_adapter_overrides_action_logits'] for r in full_rows),'full_branch_weight_zero_reference':'Atomic+State+Flip (same frozen-config trainer with Branch switch off)','full_flip_weight_zero_reference':'Atomic+State+Branch (same frozen-config trainer with Flip switch off)','full_action_head_parameter_delta_positive':bool(full_rows) and all(float(r['action_head_parameter_delta'])>0 for r in full_rows),'full_action_logits_change_after_training':bool(full_rows) and all(float(r['action_logits_change_mean_abs'])>0 for r in full_rows),'no_external_adapter_overrides_action_logits':all(bool(r['no_external_adapter_overrides_action_logits']) and not bool(r['external_adapter_overrides_action_logits']) for r in rows),'freeze_action_checkpoint':bool(full_rows) and all(not bool(r.get('freeze_action_checkpoint')) for r in full_rows),'diagnostic_only':True}
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(out,indent=2,ensure_ascii=False,sort_keys=True)); print(json.dumps({'output':str(a.output),'rows':len(rows),'full_authentic':out['full_without_rf'] and out['full_action_head_parameter_delta_positive']})); return 0
if __name__=='__main__': raise SystemExit(main())
