#!/usr/bin/env python3
"""Isolated-process ten-seed matrix for the frozen P2.3.3-r1 budget."""
from __future__ import annotations
import argparse, json, subprocess, sys, hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
METHODS=("RLOO-Atomic","GRPO-Atomic","GRPO-Stratified-4","FullInfo-ExpectedUtility","Atomic+State","Atomic+Branch","Atomic+Flip","Atomic+State+Branch","Atomic+State+Flip","Atomic+Branch+Flip","PESCO-Full")

def main(argv=None):
    p=argparse.ArgumentParser(); p.add_argument('--dataset',type=Path,required=True); p.add_argument('--root',type=Path,required=True); p.add_argument('--output',type=Path,required=True); p.add_argument('--seeds',type=int,nargs='+',default=(17,23,29,31,37,41,43,47,53,59)); p.add_argument('--methods',nargs='+',default=METHODS); p.add_argument('--finetune-steps',type=int,default=1024); p.add_argument('--sft-steps',type=int,default=256); p.add_argument('--hidden-dim',type=int,default=64); p.add_argument('--batch-size',type=int,default=64); p.add_argument('--learning-rate',type=float,default=.002); p.add_argument('--branch-loss-weight',type=float,default=.30); p.add_argument('--utility-target-weight',type=float,default=.25); p.add_argument('--atomic-target-weight',type=float,default=0.0); p.add_argument('--pairwise-weight',type=float,default=.10); p.add_argument('--flip-reference-kl-weight',type=float,default=.5); p.add_argument('--gradient-mode',choices=('sum','pcgrad'),default='sum'); p.add_argument('--pcgrad-aux-pair',action='store_true'); p.add_argument('--pcgrad-aux-orthogonal',action='store_true'); p.add_argument('--branch-head-isolated',action='store_true'); p.add_argument('--flip-head-isolated',action='store_true'); p.add_argument('--branch-formulation',choices=('sibling_advantage','expected_utility','utility_cross_entropy','soft_utility_cross_entropy','utility_improvement_soft_ce','utility_improvement_expected','top1_hinge'),default='expected_utility'); p.add_argument('--branch-trust-region',action='store_true'); p.add_argument('--branch-trust-epsilon',type=float,default=.005); p.add_argument('--stratified-factorial',action='store_true'); a=p.parse_args(argv); a.root.mkdir(parents=True,exist_ok=True)
    for seed in a.seeds:
        out=a.root/f'seed_{int(seed)}'; marker=out/'p231_result.json'
        if marker.exists(): continue
        cmd=[sys.executable,str(ROOT/'scripts/run_tier1_p233_chunk.py'),'--dataset',str(a.dataset),'--output-dir',str(out),'--seed',str(seed),'--methods',*a.methods,'--finetune-steps',str(a.finetune_steps),'--sft-steps',str(a.sft_steps),'--hidden-dim',str(a.hidden_dim),'--batch-size',str(a.batch_size),'--learning-rate',str(a.learning_rate),'--branch-loss-weight',str(a.branch_loss_weight),'--utility-target-weight',str(a.utility_target_weight),'--atomic-target-weight',str(a.atomic_target_weight),'--pairwise-weight',str(a.pairwise_weight),'--flip-reference-kl-weight',str(a.flip_reference_kl_weight),'--gradient-mode',str(a.gradient_mode),'--branch-formulation',str(a.branch_formulation)] + (['--pcgrad-aux-pair'] if a.pcgrad_aux_pair else []) + (['--pcgrad-aux-orthogonal'] if a.pcgrad_aux_orthogonal else []) + (['--branch-head-isolated'] if a.branch_head_isolated else []) + (['--flip-head-isolated'] if a.flip_head_isolated else []) + (['--branch-trust-region','--branch-trust-epsilon',str(a.branch_trust_epsilon)] if a.branch_trust_region else []) + (['--stratified-factorial'] if a.stratified_factorial else [])
        print('running seed',seed,flush=True); subprocess.run(cmd,check=True)
    payloads=[json.loads((a.root/f'seed_{int(s)}'/'p231_result.json').read_text()) for s in a.seeds]; first=payloads[0]; records=[]; logs={}; checkpoints={}
    for d in payloads:
        records.extend(d.get('records',[])); logs.update(d.get('training_logs',{})); checkpoints.update(d.get('sft_checkpoints',{}))
    config=first.get('config',{}); config_digest='sha256:'+hashlib.sha256(json.dumps(config,sort_keys=True,separators=(',',':')).encode()).hexdigest(); config['config_digest']=config_digest
    out={'schema_version':'pesco_tier1_p233_r1_method_matrix_v1','seeds':[int(s) for s in a.seeds],'methods':['SFT',*a.methods],'eval_splits':['tune','promotion'],'config':config,'config_digest':config_digest,'canonical_pair_digest':first.get('canonical_pair_digest'),'canonical_pair_count':first.get('canonical_pair_count'),'canonical_pair_contract':first.get('canonical_pair_contract',{}),'reward_tensor_audit':first.get('reward_tensor_audit',{}),'optimizer_contract':first.get('optimizer_contract',{}),'records':records,'training_logs':logs,'sft_checkpoints':checkpoints,'oracle_branch_search':[{'split':sp,'method':'Oracle-Branch-Search','question_count':len({q.get('question_id') for r in records if r.get('split')==sp for q in r.get('question_metric_rows',[]) }),'mean_regret':0.,'normalized_regret':0.,'upper_bound_only':True,'receipt_bound':True} for sp in ('tune','promotion')],'method_matrix_contract':{'sft_shared_checkpoint':True,'rl_methods_share_atomic_reward':True,'oracle_excluded_from_training':True,'authentic_factorial':True,'only_factor_switches_differ':True,'external_action_adapter_forbidden':True,'common_training_budget':int(a.finetune_steps),'isolated_seed_processes':True},'diagnostic_only':True,'formal_comparison_authorized':False}
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(out,indent=2,ensure_ascii=False,sort_keys=True)); print(json.dumps({'output':str(a.output),'records':len(records),'seeds':len(a.seeds)})); return 0
if __name__=='__main__': raise SystemExit(main())
