#!/usr/bin/env python3
"""Receipt-only P2.3.3-r1 gate with corrected mechanism comparisons."""
from __future__ import annotations
import argparse, hashlib, json, math
from pathlib import Path

def finite(x):
    try: return math.isfinite(float(x))
    except (TypeError,ValueError): return False
def bound(agg,name,kind='upper'):
    return agg.get('comparisons',{}).get(name,{}).get('delta_left_minus_right',{}).get(kind)

def main(argv=None):
    p=argparse.ArgumentParser(); p.add_argument('--matrix',type=Path,required=True); p.add_argument('--aggregate',type=Path,required=True); p.add_argument('--convergence',type=Path,required=True); p.add_argument('--shortcut',type=Path,required=True); p.add_argument('--estimator',type=Path,required=True); p.add_argument('--leakage',type=Path,required=True); p.add_argument('--stability',type=Path,required=True); p.add_argument('--attribution',type=Path,required=True); p.add_argument('--loo',type=Path,required=True); p.add_argument('--output',type=Path,required=True); a=p.parse_args(argv)
    m=json.loads(a.matrix.read_text()); g=json.loads(a.aggregate.read_text()); c=json.loads(a.convergence.read_text()); s=json.loads(a.shortcut.read_text()); e=json.loads(a.estimator.read_text()); l=json.loads(a.leakage.read_text()); st=json.loads(a.stability.read_text()); at=json.loads(a.attribution.read_text()); loo=json.loads(a.loo.read_text())
    logs=m.get('training_logs',{}); methods=[x for x in m.get('methods',[]) if x!='SFT']; cells=[x for x in ('GRPO-Atomic','Atomic+State','Atomic+Branch','Atomic+Flip','Atomic+State+Branch','Atomic+State+Flip','Atomic+Branch+Flip','PESCO-Full') if x in methods]
    full_logs=[logs.get(str(seed),{}).get('PESCO-Full',{}) for seed in m.get('seeds',[])]
    action_head_delta=bool(full_logs) and all(float(row.get('action_head_parameter_delta_norm',0))>0 for row in full_logs)
    action_logits_changed=bool(full_logs) and all(float(row.get('action_logits_change_mean_abs',0))>0 for row in full_logs)
    no_external_adapter=bool(full_logs) and all(bool(row.get('no_external_adapter_overrides_action_logits',False)) for row in full_logs)
    auth=action_head_delta and action_logits_changed and no_external_adapter
    atomic=bool(cells) and all(bool(logs.get(str(seed),{}).get(method,{}).get('atomic_reward_shared',False)) for seed in m.get('seeds',[]) for method in cells)
    budgets=[logs.get(str(seed),{}).get(method,{}).get('budget_contract',{}) for seed in m.get('seeds',[]) for method in cells]; keys=('policy_rollout_calls','counterfactual_branch_calls','exploration_seed_executions','confirmation_seed_executions','optimizer_steps','forward_backward_flops'); budget_equal=bool(budgets) and len({tuple(b.get(k) for k in keys) for b in budgets})==1
    full_rows=[r for r in m.get('records',[]) if r.get('method')=='PESCO-Full' and r.get('split')=='promotion']; asf_rows=[r for r in m.get('records',[]) if r.get('method')=='Atomic+State+Flip' and r.get('split')=='promotion']; abf_rows=[r for r in m.get('records',[]) if r.get('method')=='Atomic+Branch+Flip' and r.get('split')=='promotion']; asb_rows=[r for r in m.get('records',[]) if r.get('method')=='Atomic+State+Branch' and r.get('split')=='promotion']; f1=lambda rows: sum(float(r.get('state_macro_f1',0)) for r in rows)/len(rows) if rows else None; full_f1=f1(full_rows); abf_f1=f1(abf_rows); rec=[float(r.get('state_recall',{}).get(state)) for r in full_rows for state in ('supported','refuted','insufficient','invalid') if r.get('state_recall',{}).get(state) is not None]; invalid=[float(r.get('state_recall',{}).get('invalid')) for r in full_rows if r.get('state_recall',{}).get('invalid') is not None]
    mean_valid=lambda rows: sum(1.0-float(r.get('selected_invalid_branch_rate',1.0)) for r in rows)/len(rows) if rows else None
    mean_rep=lambda rows: sum(float(r.get('confirmation_rate',0.0) or 0.0) for r in rows)/len(rows) if rows else None
    strict=[float(v.get('metrics_by_split',{}).get('promotion',{}).get('normalized_regret')) for k,v in s.get('models',{}).items() if k.startswith('without_confirmation:') and finite(v.get('metrics_by_split',{}).get('promotion',{}).get('normalized_regret')) and v.get('status')=='completed']; full_mean=g.get('methods',{}).get('PESCO-Full',{}).get('mean_normalized_regret',float('inf'))
    d=g.get('seed_direction',{}); fam=g.get('family_direction',{})
    gates={'no_hidden_truth_used_by_estimator':bool(e.get('source_audit',{}).get('no_hidden_truth_used_by_estimator') and l.get('pass')),'all_gate_values_derived_from_receipts':bool(g.get('receipt_derived') and m.get('method_matrix_contract',{}).get('authentic_factorial')),'all_methods_share_atomic_reward':atomic,'convergence_rule_frozen_and_passed':bool(c.get('gates',{}).get('all_steps_executed') and c.get('gates',{}).get('all_seeds_executed') and all(bool(r.get('plateau_gate')) for r in c.get('records',[]) if r.get('steps')==1024)),'branch_factorial_effect_regret_ci_upper_lt_zero':finite(bound(g,'factorial-branch-main-effect')) and float(bound(g,'factorial-branch-main-effect'))<0,'full_vs_atomic_state_flip_regret_ci_upper_lt_zero':finite(bound(g,'Full-ASF')) and float(bound(g,'Full-ASF'))<0,'flip_pairrank_delta_ci_lower_gt_zero':finite(bound(g,'Full-ASB','lower')) and float(bound(g,'Full-ASB','lower'))>0,'flip_does_not_harm_regret':finite(bound(g,'Full-ASB-regret')) and float(bound(g,'Full-ASB-regret'))<=0.01,'full_state_macro_f1_noninferior_to_atomic_state':full_f1 is not None and abf_f1 is not None and full_f1+0.02>=abf_f1,'min_per_state_recall_pass':bool(rec) and min(rec)>=0.10,'invalid_recall_absolute_floor_pass':bool(invalid) and min(invalid)>=0.05,'full_vs_best_nonfull_regret_ci_upper_lt_zero':finite(bound(g,'full_vs_best_nonfull')) and float(bound(g,'full_vs_best_nonfull'))<0,'full_beats_strict_shortcut_baseline':bool(strict) and full_mean<min(strict),'at_least_8_of_10_seed_directions_positive':sum(bool(x.get('full_better')) for x in d.values())>=8,'family_majority_direction_positive':bool(fam) and sum(bool(v) for v in fam.values())>=((len(fam)+1)//2),'leave_one_family_out_robust':loo.get('ten_family_runs_completed') is True,'environment_execution_budget_matched':budget_equal,'selected_action_validity_noninferior':mean_valid(full_rows) is not None and mean_valid(asb_rows) is not None and mean_valid(full_rows)+0.02>=mean_valid(asb_rows),'selected_action_replication_noninferior':mean_rep(full_rows) is not None and mean_rep(asb_rows) is not None and mean_rep(full_rows)+0.05>=mean_rep(asb_rows),'reward_weight_stability_pass':bool(st.get('pass')),'full_action_head_parameter_delta_positive':action_head_delta,'full_action_logits_change_after_training':action_logits_changed,'no_external_adapter_overrides_action_logits':no_external_adapter,'policy_authenticity':auth and at.get('full_without_rf') is True}
    out={'schema_version':'pesco_p233_r1_gate_v1','status':'GO' if all(gates.values()) else 'NO_GO','p233_go':gates,'receipt_sources':{'matrix':str(a.matrix),'aggregate':str(a.aggregate),'convergence':str(a.convergence),'shortcut':str(a.shortcut),'estimator':str(a.estimator),'leakage':str(a.leakage),'stability':str(a.stability),'attribution':str(a.attribution),'loo':str(a.loo)},'thresholds':{'state_f1_noninferiority_margin':.02,'min_per_state_recall':.10,'invalid_recall_floor':.05,'full_vs_asb_regret_noninferiority_margin':.01},'diagnostic_only':True,'private_data_accessed':False}; unsigned=json.dumps(out,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode(); out['audit_sha256']='sha256:'+hashlib.sha256(unsigned).hexdigest(); a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(out,indent=2,ensure_ascii=False,sort_keys=True)); print(json.dumps(out,indent=2)); return 0 if out['status']=='GO' else 2
if __name__=='__main__': raise SystemExit(main())
