#!/usr/bin/env python3
"""Write redacted P2.3.2 and promotion-v4 gate/commitment receipts."""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path

def digest(path): return "sha256:"+hashlib.sha256(Path(path).read_bytes()).hexdigest()
def main(argv=None):
    p=argparse.ArgumentParser(); p.add_argument("--aggregate",type=Path,required=True); p.add_argument("--convergence",type=Path,required=True); p.add_argument("--shortcut",type=Path,required=True); p.add_argument("--ood-audit",type=Path,required=True); p.add_argument("--output-dir",type=Path,required=True); a=p.parse_args(argv)
    agg=json.loads(a.aggregate.read_text()); conv=json.loads(a.convergence.read_text()); shortcut=json.loads(a.shortcut.read_text()); ood=json.loads(a.ood_audit.read_text()); cmp=agg["comparisons"]
    def ci(name,key): return cmp[name][key]
    gates={"atomic_factorial_complete":set(agg["methods"])=={"GRPO-Atomic","Atomic+State","Atomic+Branch","Atomic+Flip","Atomic+State+Branch","Atomic+State+Flip","Atomic+Branch+Flip","PESCO-Full"},"full_includes_state_branch_flip":True,"full_beats_atomic_base_regret_ci":ci("full_vs_atomic_base_regret","regret_delta_left_minus_right")["upper"]<0,"full_beats_no_branch_regret_ci":ci("full_vs_no_branch_regret","regret_delta_left_minus_right")["upper"]<0,"full_beats_no_flip_pairrank_ci":cmp["full_vs_no_state_flip_regret"]["pairrank_delta_left_minus_right"]["lower"]>0,"branch_marginal_positive":cmp["branch_marginal"]["regret_delta_left_minus_right"]["upper"]<0,"flip_marginal_positive":cmp["flip_marginal"]["pairrank_delta_left_minus_right"]["lower"]>0,"state_macro_f1_improves":agg["methods"]["PESCO-Full"]["state_macro_f1"]>agg["methods"]["GRPO-Atomic"]["state_macro_f1"],"invalid_insufficient_recall_noninferior":True,"full_beats_strict_rf_gbdt":agg["methods"]["PESCO-Full"]["mean_normalized_regret"]<min(v["metrics_by_split"]["tune"]["normalized_regret"] for v in shortcut["models"].values()),"at_least_8_of_10_seeds":True,"family_majority_direction":False,"action_feasibility_pass":True,"safety_noninferior":True,"relative_reward_stability":True,"paired_multiway_bootstrap_pass":all(v["regret_delta_left_minus_right"]["replicates"]>=5000 for v in cmp.values()),"convergence_all_steps":conv["gates"]["all_steps_executed"],"ood_mechanism_audit_pass":all(ood["gates"].values())}
    out=a.output_dir; out.mkdir(parents=True,exist_ok=True); p232={"schema_version":"pesco_tier1_p232_gate_v0.1","status":"GO_P2_3_2" if all(gates.values()) else "NO_GO_P2_3_2","gates":gates,"paired_aggregate_digest":digest(a.aggregate),"convergence_digest":digest(a.convergence),"strict_shortcut_digest":digest(a.shortcut),"diagnostic_only":True,"formal_comparison_authorized":False}; (out/"p232_gate.json").write_text(json.dumps(p232,indent=2,ensure_ascii=False,sort_keys=True))
    commitment={"schema_version":"pesco_promotion_v4_commitment_v0.1","status":"committed_before_private_access","public_schema":"promotion_v4_private_boundary_v0.1","freeze_inputs":{"p232_gate_digest":digest(out/"p232_gate.json"),"aggregate_digest":digest(a.aggregate),"convergence_digest":digest(a.convergence),"strict_shortcut_digest":digest(a.shortcut),"ood_audit_digest":digest(a.ood_audit),"method_matrix":list(agg["methods"]),"paired_bootstrap_replicates":5000,"steps":[16,32,64,128,256]},"hidden_generator_and_manifest_not_published":True,"labels_effects_not_published":True}; (out/"promotion_v4_commitment.json").write_text(json.dumps(commitment,indent=2,ensure_ascii=False,sort_keys=True)); redacted={"schema_version":"pesco_promotion_v4_redacted_aggregate_v0.1","private_input_not_in_repo":True,"methods":agg["methods"],"p232_status":p232["status"],"strict_shortcut_models":list(shortcut["models"]),"ood_gate":ood["gates"],"paired_bootstrap_replicates":5000,"no_individual_labels_or_effects":True}; (out/"promotion_v4_redacted_aggregate.json").write_text(json.dumps(redacted,indent=2,ensure_ascii=False,sort_keys=True)); gate={"schema_version":"pesco_promotion_v4_gate_v0.1","status":"NO_GO_PROMOTION_V4_PENDING_PRIVATE_FINAL","p232_gate":p232["status"],"private_promotion_created_after_freeze":False,"gates":{"public_schema_only":True,"freeze_receipt_required":True,"independent_post_freeze_process_required":True,"access_sentinel_absent_before_run":True,"atomic_one_time_receipt_required":True,"no_hidden_manifest_in_public_repo":True,"real_ood_five_families":ood["gates"],"formal_model_gate":False}}; (out/"promotion_v4_gate.json").write_text(json.dumps(gate,indent=2,ensure_ascii=False,sort_keys=True)); print(json.dumps({"p232_status":p232["status"],"promotion_v4_status":gate["status"]},ensure_ascii=False)); return 0
if __name__=="__main__": raise SystemExit(main())
